#!/bin/sh
# postrm script for fluentd
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    remove)
        # Remove logs
        rm -rf /var/log/fluentd

        # remove **only** empty data dir
        rmdir -p --ignore-fail-on-non-empty /var/lib/fluentd
    ;;

    purge)
        # Remove logs and data
        rm -rf /var/log/fluentd /var/lib/fluentd

        # Remove user/group
        deluser fluentd || true
        delgroup fluentd || true
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Nothing to do here
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

if [ "$1" = "purge" ] ; then
        update-rc.d fluentd remove >/dev/null
fi

exit 0

